In [6]:
import numpy as np
import pandas as pd
import matplotlib as mpl
from ipysheet import from_dataframe, to_dataframe
from ipywidgets import FloatSlider, IntSlider, Image

### Length scale

In [24]:
delta_nu = (2*np.pi-1)/720 # viscous len scale
Delta = 2*np.pi/2**10 # grid size for LEVEL 10
k = 4 # wave number
z0 = 0.11*delta_nu
a = np.array((0.1,0.15,0.2))/k
print('k\delta_{nu} = %g' %(k*delta_nu))
print('kz_0 = %g' % (k*z0))
print('k\Delta = %g' %(k*Delta))

print('a/\Delta = ')
print(a/Delta)
print('\delta_{nu}/\Delta = %g' %(delta_nu/Delta))
print('\lambda/\Delta = %g' %(2*np.pi/(k*Delta)))
print(delta_nu*k)

k\delta_{nu} = 0.029351
kz_0 = 0.00322861
k\Delta = 0.0245437
a/\Delta = 
[4.07436654 6.11154981 8.14873309]
\delta_{nu}/\Delta = 1.19587
\lambda/\Delta = 256
0.029351029484331034


### Time scale

In [21]:
nu_a = 0.00183
ustar = 0.25
t_nu = nu_a/ustar**2
print(t_nu)

0.02928


In [9]:
# Reference https://github.com/QuantStack/ipysheet/blob/master/examples/widget_cell.ipynb
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([False, True, False, False], dtype='bool'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})

df2.loc[[0, 2], ['B']] = np.nan

sheet2 = from_dataframe(df2)
sheet2

Sheet(cells=(Cell(choice=[], column_end=0, column_start=0, row_start=0, squeeze_row=False, type='numeric', val…

In [24]:
df = pd.DataFrame({'c/u*': (2,3,4,6,8),
                   'g': (1,2.25,4,9,16),
                   'omega': (2.005,3.007,4.010,6.015,8.020),
                   'T/t_nu': (2*np.pi/np.array((2.005,3.007,4.010,6.015,8.020)))/0.0293,
                   'E': 'boo',
                   'F': 'foo'})

sheet = from_dataframe(df)
sheet

Sheet(cells=(Cell(choice=[], column_end=0, column_start=0, numeric_format='0[.]0', row_end=4, row_start=0, squ…

In [ ]:
df_new = to_dataframe(sheet)
df_new

In [16]:
np.array((1,2.25,4,9,16))*np.array((2.005,3.007,4.010,6.015,8.020))

array([  2.005  ,   6.76575,  16.04   ,  54.135  , 128.32   ])

In [5]:
(2*np.pi/np.array((2.005,3.007,4.010,6.015,8.020)))/0.0293

array([106.95420676,  71.31466064,  53.47710338,  35.65140225,
        26.73855169])